version: '3.9'

services:
  mongo:
    image: mongo:7.0
    container_name: vaultx-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: vaultx
      MONGO_INITDB_ROOT_PASSWORD: vaultx-secret
      MONGO_INITDB_DATABASE: vaultx
    volumes:
      - vaultx_mongo:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', 'db.adminCommand("ping").ok']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vaultx-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - vaultx_redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  vaultx_mongo:
  vaultx_redis:
